global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'benchmark-net8'
    static_configs:
      - targets: ['benchmark-net8:8081']
    scrape_interval: 10s

  - job_name: 'benchmark-net9'
    static_configs:
      - targets: ['benchmark-net9:8082']
    scrape_interval: 10s